### PR TITLE
Allow channel for stereo split

### PR DESCRIPTION
**Pull request by mpessa**
Allow channel to be built in the XML in order to split L/R stereo audio into separate videos.

QA Steps:
Run `rspec ./spec/video_format_editing_spec.rb`

### CODE REVIEW

**Review by kylemellander — DISMISSED** [review]

**Review by jerelmiller — APPROVED** [review]

**Review by zulaica — DISMISSED** [review]
👍

**Review by kylemellander — COMMENTED** [review]
is that the format that is it supposed to be in?  Is that a change on the client?

**Comment by mpessa** [comment]
That's the correct format. I was using an incorrect format originally that somehow worked in my vagrant machine but threw an error when the spec was ran anywhere else.

**Review by kylemellander — APPROVED** [review]

**Review by jsheetsPDX — APPROVED** [review]

**Comment by jsheetsPDX** [comment]
Specs pass.

**Pull request merged**
